### ISSUE TITLE
Add optional Code Review step

### ISSUE THREAD

**Issue by iamerikjolson** [80-20/ProcessManagement#1]

**Comment by iambriansreed** [comment]
Can I assign myself here and update the docs. @erikpmp @travisstokes? It will make a fork for me and I will submit my changes with a PR.

This is a year old. 😿

**Comment by iambriansreed** [comment]
![image](https://cloud.githubusercontent.com/assets/2301464/20452165/7bdf82a6-add1-11e6-9d96-73d95643988e.png)

Possible Color...

**Comment by iamerikjolson** [comment]
Yes @iambriansreed, please do. But let's use a consistent color with "In Development" because it's really a sub-step of development. 

Ironically this repo does not yet use our process labels. I'll fix that now.

**Comment by iambriansreed** [comment]
![image](https://cloud.githubusercontent.com/assets/2301464/20497255/7dd6046e-aff6-11e6-9a45-ce61d36c117a.png)

@erikpmp eh?

**Comment by iamerikjolson** [comment]
Looks good

**Comment by iambriansreed** [comment]
See https://github.com/80-20/ProcessManagement/pull/4

**Comment by iambriansreed** [comment]
I can't change assignment on this issue @erikpmp.

**Comment by iamerikjolson** [comment]
This has been completed.
