### ISSUE TITLE
Draft Requirements Management Process

### ISSUE THREAD

**Issue by iamerikjolson** [80-20/ProcessManagement#5]
Things like:

* Use Google Doc to create a PRD. 
* The PRD contains the following sections: 
  * Vision
  * Background
  * Risks
  * Issues
  * Individual Requirements
* Requirement names in the format, "[Noun] - [Action]". Ex: "Users - Add/Edit"
* The client signs off on v1 of the PRD. Save a PDF signed copy in the project folder in Google Drive with the intent that it is "frozen" and will not be modified. Number it version v1.0.
* Create one GH issue per requirement.
  * GH Issue title should be named "[req name] (req #)", ex: "Users - Add/Edit (req #15)". 
  * Add a deep link to the requirement in the Google Doc version of the PRD. Create a deep link by click on the requirement heading in the Google Doc and adding a bookmark (Insert menu >> bookmark), then copy the URL to the bookmark and paste into GH.
* Create milestones two weeks apart from one another. 
  * Milestone name v0.01, v0.02, etc. (leading up to the same version of the PRD, so when all milestones are done the last minor version will be changed in Production to match the PRD version it was built against).
  * Set due dates.
* Assign issues to each milestone.
* Use milepost to create an overall project schedule. Send to the team and client.

**Versioning the PRD**

If a change is needed then a decision needs to be made whether the change should affect the code currently being developed.

If yes = **Minor PRD versioning (e.g, v1.1)**

Update the previously approved PRD (e.g. v1.0) by:

* Modify the document as needed.
* Annotate change in the revision log. A revision log is only needed after the PRD for a major version. Ex: In PRD v1.0, no revision log is needed. In PRD v1.1, the revision log will have one entry and clarify what was changed between v1.0 and v1.1. Include one entry for each subsequent minor revision. All increments should be in ".1"s.
* Annotate the current version on the cover page
* Update the file name of the Google Doc (not the PDF) to the new version number.

If no = **Major PRD version** (eg v2.0)

Create a copy of the Google Doc PRD and use it as the basis for documenting the future changes.

* No revision log required
* Change the version number on the cover page and Google Doc file name.
* Modify as needed.

Note: Do not modify the previous major version of the Google Doc PRD, otherwise you will modify the expectation of the work that is currently being developed.

**Comment by iamerikjolson** [comment]
Draft in this repo's wiki. Once we like it we'll move to the readme file.

**Comment by sheelac** [comment]
@erikpmp We need to add "Features" under the "Sections" list above.

**Comment by sheelac** [comment]
@erikpmp I can't edit this repo - please update my rights.
